# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text=b'This field is autofilled while saving.', unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
