# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, help_text=b'This field is autofilled while saving.', unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
