# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0003_auto_20160605_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('context', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.Individual', verbose_name=b'individual')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
    ]
