# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', b'SESSION_ON'), (b'INACTIVE', b'SESSION_OFF')], default=b'INACTIVE', max_length=64),
        ),
    ]
