# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[(b'A', b'ASSERT'), (b'D', b'DEBUG'), (b'E', b'ERROR'), (b'I', b'INFO'), (b'V', b'VERBOSE'), (b'W', b'WARN'), (b'ALL', b'ALL_LOGS')], default=b'V', max_length=64),
        ),
        migrations.AlterField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
