# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
        ('log', '0002_auto_20160603_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='individual.Individual', verbose_name=b'logs'),
        ),
    ]
