# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='individual.Individual', verbose_name=b'individual'),
        ),
    ]
