# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20160604_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.Individual', verbose_name=b'individual'),
        ),
    ]
