# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20160604_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
