# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_log_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session', verbose_name=b'session'),
        ),
    ]
