# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_auto_20160602_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(max_length=100)),
                ('os', models.CharField(default=b'', max_length=32)),
                ('version', models.CharField(default=b'', max_length=32)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name=b'questions')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
