# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name=b'client'),
        ),
    ]
