# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_auto_20160604_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
